# Generated by Django 3.1.12 on 2024-12-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='date',
            new_name='created_at',
        ),
    ]
